[base]
id = 2
name = "monitor-guest"
vm_type = 1
cpu_num = 1
phys_cpu_ids = [1]

[kernel]
entry_point = 0x8020_0000
image_location = "memory"
kernel_path = "../../../../../../target/aarch64-unknown-none-softfloat/release/ax-monitor-guest.bin"
kernel_load_addr = 0x8020_0000
dtb_load_addr = 0x8000_0000

memory_regions = [
  [0x8000_0000, 0x2000_0000, 0x7, 0],
]

[devices]
interrupt_mode = "passthrough"
passthrough_addresses = [
    { base_gpa = 0x9000000, length = 0x1000 },
]
passthrough_devices = [["/"]]
excluded_devices = []
emu_devices = []
