extern crate alloc;
use alloc::vec;
use alloc::vec::Vec;
use alloc::string::String;
use alloc::string::ToString;
use alloc::format;


use crate::capture::export;
use crate::capture::log;
use crate::capture::modules;
use crate::capture::register::{self, CrashVcpuRegs};
use crate::capture::storage;
use crate::capture::memory;
use crate::monitor::event::CrashEvent;
use crate::recovery::analyzer;
use crate::recovery::kallsyms::{self, KallsymsAddrs};
use crate::recovery::report;
use crate::recovery::symbol::SymbolTable;
use serde::{Deserialize, Serialize};

/// Target VM configuration — should be set from VM config at startup.
const TARGET_VM_ID: u64 = 1;
const TARGET_VCPU_COUNT: u64 = 1;

/// Guest physical memory regions to dump (must match target VM memory layout).
/// Linux kernel Image is loaded at the start of the VM's memory region.
/// 64 MiB covers: kernel image (~22 MiB), BSS, data, slab allocator, and
/// the common kernel stack region. Satisfies the "partial dump" requirement.
/// From AxVisor log: gpa=GPA:0x223600000, size=256 MiB.
const MEMORY_REGIONS: &[(u64, usize)] = &[
    (0x223600000, 0x0400_0000),  // 64 MiB — kernel + data + stacks
];

/// Guest kernel linear mapping offset (GVA → GPA).
/// Linux ARM64 uses PAGE_OFFSET = 0xffff_0000_0000_0000 (48-bit VA).
/// So virtual address → physical: GPA = VA - PHYS_VIRT_OFFSET.
const PHYS_VIRT_OFFSET: u64 = 0xffff_0000_0000_0000;

/// Guest physical memory base address (from target VM config).
/// The target VM's RAM starts at GPA 0x8000_0000 with 256 MB.
/// The hypervisor maps this to HPA MEMORY_REGIONS[0].0 (currently 0x223600000).
/// Translation: HPA = guest_PA - GUEST_PHYS_BASE + MEMORY_REGIONS[0].0
const GUEST_PHYS_BASE: u64 = 0x8000_0000;

/// Kernel image virtual address base (KIMAGE_VADDR).
const KERNEL_IMAGE_TEXT_VA: u64 = 0xffff_8000_8000_0000;

/// Path to the target kernel ELF (with symbol table) inside the monitor guest's filesystem.
/// Set to empty string to disable ELF symbol resolution (kallsyms will be used instead).
/// The ELF must be baked into the monitor-guest image at build time.
const KERNEL_ELF_PATH: &str = "";

/// Kernel base virtual address for symbol table lookups.
/// If the ELF has absolute virtual addresses (ET_EXEC linked at KERNEL_BASE_VADDR),
/// set this to 0 so that `addr - 0 = addr` matches `sym.st_value` directly.
/// If the ELF has relative offsets (PIE), set this to PHYS_VIRT_OFFSET + kernel_load_addr.
const KERNEL_BASE_ADDR: u64 = 0;

/// Kallsyms GPA configuration for the target Linux kernel.
/// Generated by tools/gen-kallsyms-config.sh from vmlinux (Alpine linux-virt 6.12.94).
/// Set to `None` to disable kallsyms-based symbol resolution (fall back to ELF path).
const KALLSYMS_ADDRS: Option<KallsymsAddrs> = Some(KallsymsAddrs {
    // Kernel loaded at GPA 0x223600000 (MAP_IDENTICAL base)
    // Formula: GPA = VA - 0xffff800080000000 + 0x223600000
    num_syms_gpa:         0x2_2436_05d8,
    relative_base_gpa:    0x2_244c_df50,
    offsets_gpa:          0x2_2447_aa70,
    names_gpa:            0x2_2436_05e0,
    token_table_gpa:      0x2_2447_a4e0,
    token_index_gpa:      0x2_2447_a870,
    markers_gpa:          0x2_2447_9fa8,
});

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemorySegment {
    pub base_gpa: u64,
    pub size: usize,
    pub path: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct CrashSnapshot {
    pub event: CrashEvent,
    /// Per-vCPU register states captured at crash time. (vcpu_id, regs)
    pub vcpu_regs: Vec<(u64, CrashVcpuRegs)>,
    /// Optional memory dump segments.
    pub memory_segments: Vec<MemorySegment>,
    /// Kernel log buffer text, if capture succeeded.
    pub kernel_log: Option<String>,
    /// Loaded kernel module information.
    pub modules: Vec<modules::ModuleInfo>,
}

pub fn capture_snapshot(event: CrashEvent) {
    let timestamp = boot_timestamp();
    ax_std::println!("[capture] start snapshot (event={:?})", event);

    // Ensure /vmcore/ directory exists for memory dump files.
    let _ = ax_std::fs::create_dir("/vmcore");

    // Step 1: Freeze the target VM and read all vCPU registers via HVC.
    let vcpu_regs = match register::freeze_and_read_all(TARGET_VM_ID, TARGET_VCPU_COUNT) {
        Ok(regs) => {
            ax_std::println!("[capture] captured {} vCPU register sets", regs.len());
            for (id, r) in &regs {
                ax_std::println!(
                    "  VCpu[{}] PC={:#018x} SP={:#018x}",
                    id, r.elr_el1, r.sp_el0
                );
            }
            regs
        }
        Err(e) => {
            ax_std::println!("[capture] register capture failed: {}", e);
            ax_std::println!("[capture] falling back to simulated register data");
            vec![(0, CrashVcpuRegs::default())]
        }
    };

    // Step 2: Dump guest physical memory via HVC #9.
    // Keep both the metadata (for vmcore JSON) and the raw data (for analysis closure).
    let memory_segments: Vec<MemorySegment>;
    let memory_regions_data: Vec<(u64, Vec<u8>)> = match memory::dump_memory_regions(TARGET_VM_ID, MEMORY_REGIONS) {
        Ok(segments) => {
            let mut out = Vec::new();
            for (base, data) in &segments {
                let file_name = alloc::format!("memory_{:08x}_{}.bin", base, timestamp);
                let path = alloc::format!("/vmcore/{}", file_name);
                match ax_std::fs::write(&path, data) {
                    Ok(_) => {
                        ax_std::println!("[capture] memory dump saved: {} ({} bytes)", file_name, data.len());
                        out.push(MemorySegment {
                            base_gpa: *base,
                            size: data.len(),
                            path: file_name,
                        });
                    }
                    Err(e) => {
                        ax_std::println!("[capture] failed to write memory dump {}: {}", path, e);
                    }
                }
            }
            memory_segments = out;
            segments
        }
        Err(e) => {
            ax_std::println!("[capture] memory dump failed: {}", e);
            memory_segments = Vec::new();
            Vec::new()
        }
    };
    // Step 3: Collect kernel log buffer.
    let kernel_log = match log::collect_kernel_log(TARGET_VM_ID, Some(0x224_c57f_b8), 64 * 1024) {
        Ok(result) => {
            ax_std::println!("[capture] kernel log collected: {} chars", result.raw_text.len());
            Some(result.raw_text)
        }
        Err(e) => {
            ax_std::println!("[capture] kernel log skipped: {}", e);
            None
        }
    };

    // Step 4: Collect loaded kernel module information via HVC #9.
    let modules = match modules::collect_modules(TARGET_VM_ID, None) {
        Ok(result) => {
            ax_std::println!(
                "[capture] modules: {} found (method: {})",
                result.modules.len(),
                result.method,
            );
            for m in &result.modules {
                ax_std::println!("  module: {} @ {:#x} ({} bytes)", m.name, m.base_addr, m.size);
            }
            result.modules
        }
        Err(e) => {
            ax_std::println!("[capture] modules skipped: {}", e);
            Vec::new()
        }
    };

    let snapshot = CrashSnapshot {
        event,
        vcpu_regs,
        memory_segments: memory_segments.clone(),
        kernel_log,
        modules,
    };

    ax_std::println!("[capture] snapshot captured");

    // Step 5: Save vmcore to persistent storage.
    if let Ok(vmcore_path) = storage::save_vmcore(&snapshot) {
        ax_std::println!("[capture] vmcore saved at: {}", vmcore_path);

        // Step 6: Load vmcore and run recovery analysis.
        if let Some(vmcore) = storage::load_vmcore(&vmcore_path) {
            ax_std::println!("[recovery] starting crash analysis...");

            // Build a memory reader closure that translates Guest Virtual Address
            // → Guest Physical Address and looks up data in the dumped segments.
            // Falls back to HVC #9 (CrashReadGuestMem) for addresses not in the dump.
            let mem_reader = |addr: u64| -> Option<u64> {
                // GVA → GPA: handle kernel image, linear mapping, and others
                let gpa = if addr >= KERNEL_IMAGE_TEXT_VA
                    && addr < KERNEL_IMAGE_TEXT_VA + 0x8000_0000
                {
                    // Kernel image region (2 GiB): VA - _text_va → base_gpa + offset
                    addr.wrapping_sub(KERNEL_IMAGE_TEXT_VA)
                        .wrapping_add(MEMORY_REGIONS[0].0)
                } else if addr >= PHYS_VIRT_OFFSET
                    && addr < 0xffff_8000_0000_0000u64
                {
                    // Linear mapping: VA = PAGE_OFFSET + guest_PA
                    // guest_PA = VA - PAGE_OFFSET
                    // HPA = MEMORY_REGIONS[0].0 + (guest_PA - GUEST_PHYS_BASE)
                    let guest_pa = addr.wrapping_sub(PHYS_VIRT_OFFSET);
                    guest_pa.wrapping_sub(GUEST_PHYS_BASE)
                        .wrapping_add(MEMORY_REGIONS[0].0)
                } else {
                    // Raw GPA (for debugging with the `memory` command)
                    addr
                };
                // Try dump segments first
                if let Some((base, data)) = memory_regions_data
                    .iter()
                    .find(|(base, data)| gpa >= *base && gpa < *base + data.len() as u64)
                {
                    let offset = (gpa - *base) as usize;
                    if offset + 8 <= data.len() {
                        let mut bytes = [0u8; 8];
                        bytes.copy_from_slice(&data[offset..offset + 8]);
                        return Some(u64::from_le_bytes(bytes));
                    }
                }
                // Fallback: read from frozen target VM via HVC #9
                let mut buf = [0u8; 8];
                register::read_guest_mem(TARGET_VM_ID, gpa, &mut buf).ok()?;
                Some(u64::from_le_bytes(buf))
            };

            // Try to load kernel symbol table for function name resolution.
            // Priority: kallsyms (from frozen VM memory) > embedded ELF > None
            let sym = 'load: {
                // Try kallsyms first (reads from frozen target VM via HVC #9)
                if let Some(ref addrs) = KALLSYMS_ADDRS {
                    match kallsyms::read_kallsyms(
                        TARGET_VM_ID,
                        addrs,
                        &register::read_guest_mem,
                    ) {
                        Ok(table) => {
                            ax_std::println!(
                                "[recovery] kallsyms loaded: {} symbols",
                                table.len(),
                            );
                            break 'load Some(table);
                        }
                        Err(e) => {
                            ax_std::println!("[recovery] kallsyms unavailable: {}", e);
                        }
                    }
                }

                // Fall back to embedded ELF symbol file
                if !KERNEL_ELF_PATH.is_empty() {
                    match SymbolTable::from_kernel_elf(KERNEL_ELF_PATH, KERNEL_BASE_ADDR) {
                        Ok(table) => {
                            ax_std::println!(
                                "[recovery] symbol table loaded from ELF: {} symbols",
                                table.len(),
                            );
                            break 'load Some(table);
                        }
                        Err(e) => {
                            ax_std::println!("[recovery] ELF symbol table unavailable: {}", e);
                        }
                    }
                }

                None
            };

            let result = analyzer::analyze(
                &vmcore,
                &mem_reader,
                sym.as_ref(),
            );

            // Print analysis summary to console.
            ax_std::println!("[recovery] analysis summary: {}", result.summary);
            for cause in &result.possible_causes {
                ax_std::println!("[recovery]   - {}", cause);
            }

            // Step 5: Save analysis reports (with _analysis suffix to avoid overwriting vmcore).
            let report_base = alloc::format!("{}_analysis", vmcore_path.trim_end_matches(".json"));
            let (json_path, md_path) = match report::save_reports(&result, &report_base) {
                Ok(paths) => {
                    ax_std::println!("[recovery] analysis reports saved:");
                    ax_std::println!("  JSON: {}", paths.0);
                    ax_std::println!("  MD:   {}", paths.1);
                    paths
                }
                Err(e) => {
                    ax_std::println!("[recovery] failed to save reports: {}", e);
                    // Generate placeholder paths so downstream export still works
                    (alloc::format!("{}.json", report_base), alloc::format!("{}.md", report_base))
                }
            };

            // Step 6: Export all files to hypervisor storage via HVC #11.
            // Re-read saved files and send them to the hypervisor.
            let mut export_entries: Vec<(String, Vec<u8>)> = Vec::new();

            // 6a — vmcore JSON
            if let Ok(content) = ax_std::fs::read_to_string(&vmcore_path) {
                let fname = vmcore_path.rsplit('/').next().unwrap_or("vmcore.json");
                export_entries.push((fname.to_string(), content.into_bytes()));
            }

            // 6b — analysis reports (best-effort, skip if save_reports failed)
            for path in [&json_path, &md_path] {
                if let Ok(content) = ax_std::fs::read_to_string(path) {
                    let fname = path.rsplit('/').next().unwrap_or("report");
                    export_entries.push((fname.to_string(), content.into_bytes()));
                }
            }

            // 6c — memory dump binaries
            for seg in &memory_segments {
                let mem_path = alloc::format!("/vmcore/{}", seg.path);
                if let Ok(data) = ax_std::fs::read(&mem_path) {
                    let fname = seg.path.rsplit('/').next().unwrap_or("memory.bin");
                    export_entries.push((fname.to_string(), data));
                }
            }

            if !export_entries.is_empty() {
                let refs: Vec<(&str, &[u8])> = export_entries
                    .iter()
                    .map(|(n, d)| (n.as_str(), d.as_slice()))
                    .collect();
                export::export_files(&refs);
            } else {
                ax_std::println!("[export] no files to export");
            }

            // Step 7: Enter interactive crash analysis console.
            ax_std::println!("[console] entering interactive analysis shell...");
            crate::recovery::console::interactive_shell(
                &vmcore,
                &mem_reader,
                sym.as_ref(),
                &result,
            );
        } else {
            ax_std::println!("[recovery] failed to load vmcore for analysis");
        }
    } else {
        ax_std::println!("[capture] failed to save vmcore");
    }
}

/// Monotonic counter used as timestamp for file names.
fn boot_timestamp() -> u64 {
    use core::sync::atomic::{AtomicU64, Ordering};
    static TS: AtomicU64 = AtomicU64::new(0);
    TS.fetch_add(1, Ordering::Relaxed)
}