#!/bin/bash
# Generate kallsyms GPA configuration for the monitor guest.
#
# Usage:
#   ./gen-kallsyms-config.sh <path-to-vmlinux>
#
# Output: Rust code snippet with KallsymsAddrs GPAs, ready to paste into snapshot.rs
#
# Background:
#   kallsyms is the Linux kernel's symbol table, stored in compressed form in
#   the .rodata section. After a crash, the monitor guest reads it directly
#   from the frozen target VM's memory via HVC #9 and decodes it.
#
# Address conversion:
#   Linux ARM64 kernel image VA → GPA:
#     GPA = VA - KIMAGE_VADDR + KERNEL_LOAD_PA
#   Where:
#     KIMAGE_VADDR   = 0xffff_8000_8000_0000 (ARM64 kernel image virtual base)
#     KERNEL_LOAD_PA = 0x223400000            (VM[1] memory base)
#     PHYS_VIRT_OFFSET = 0xffff_0000_0000_0000 (48-bit VA linear map offset)

set -euo pipefail

VMLINUX="${1:?Usage: $0 <path-to-vmlinux>}"
KIMAGE_VADDR="0xffff800080000000"
KERNEL_LOAD_PA="0x223600000"

if [ ! -f "$VMLINUX" ]; then
    echo "Error: vmlinux not found at '$VMLINUX'"
    exit 1
fi

echo "// Auto-generated by gen-kallsyms-config.sh"
echo "// Source: $VMLINUX"
echo "// Date: $(date -Iseconds)"
echo ""

# Convert VA to GPA using kernel image mapping
va_to_gpa() {
    local va="$1"
    # Strip 0x prefix for arithmetic
    local va_dec=$((va))
    local kimage_vaddr_dec=$((KIMAGE_VADDR))
    local kernel_load_pa_dec=$((KERNEL_LOAD_PA))

    # Check if VA is in kernel image range
    if [ $va_dec -ge $kimage_vaddr_dec ]; then
        local offset=$((va_dec - kimage_vaddr_dec))
        local gpa=$((kernel_load_pa_dec + offset))
        printf "0x%x" "$gpa"
    else
        # Use linear map offset (for addresses in vmalloc/modules area)
        echo "WARNING: VA not in kernel image range: $va" >&2
        printf "0x%x" "$va"
    fi
}

# Symbol names to lookup
SYMBOLS=(
    "kallsyms_num_syms"
    "kallsyms_relative_base"
    "kallsyms_offsets"
    "kallsyms_names"
    "kallsyms_token_table"
    "kallsyms_token_index"
    "kallsyms_markers"
)

echo "KallsymsAddrs {"

for sym in "${SYMBOLS[@]}"; do
    line=$(aarch64-linux-gnu-nm "$VMLINUX" 2>/dev/null | grep -E " [DdRr] $sym$" | head -1)
    if [ -z "$line" ]; then
        # Try without trailing stuff
        line=$(aarch64-linux-gnu-nm "$VMLINUX" 2>/dev/null | grep -E " [DdRr] .*$sym" | head -1)
    fi
    if [ -n "$line" ]; then
        va_hex=$(echo "$line" | awk '{print $1}')
        va_dec=$((16#$va_hex))
        gpa=$(va_to_gpa $va_dec)
        echo "    // $line"
        echo "    ${sym}_gpa: $gpa,"
    else
        echo "    // WARNING: $sym not found in vmlinux!"
        echo "    ${sym}_gpa: 0, // UNKNOWN"
    fi
done

echo "}"
echo ""
echo "// num_syms value check:"
aarch64-linux-gnu-nm "$VMLINUX" 2>/dev/null | grep 'kallsyms_num_syms' | head -1
echo "// (read u32 at GPA to confirm)"
